os: Visual Studio 2019

clone_depth: 1

branches:
  only:
    - master
    - develop
    - next
    - /dev.*/
    - /release-.*/

environment:
  github_access_token:
    secure: "ogfTv7V0xR13ETjrC+koS7ZURfl0KLRfwcjYBexoiB1gcc5pppO/H42BopJWl0ua"

install:
  # NSIS Paths
  # https://www.appveyor.com/docs/build-environment/#tools
  - set PATH=%PATH%;C:\Program Files (x86)\NSIS


before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  # Build required dlls
  - cd includes\BookwormUWPServices
  - nuget restore
  - msbuild /t:Build /p:Configuration=Release
  - cd %APPVEYOR_BUILD_FOLDER%


build_script:
  # 32-bit version
  - ps: Write-Host "Building the 32-bit variant."
  - C:\Python39\python.exe -m venv .venv32
  - call ".venv32\Scripts\activate.bat"
  - python -m pip install invoke
  - invoke build
  - invoke create-portable
  - deactivate
  # 64-bit version
  - ps: Write-Host "Building the 64-bit variant."
  - C:\Python39-x64\python.exe -m venv .venv64
  - call ".venv64\Scripts\activate.bat"
  - python -m pip install invoke
  - invoke build
  - invoke create-portable
  # Update the release info file
  - invoke update-version-info


artifacts:
  - path: scripts\Bookworm*setup.exe
  - path: scripts\Bookworm*update.bundle
  - path: scripts\Bookworm*portable.zip
  - path: scripts\release-info.json


on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG_NAME -and $env:APPVEYOR_REPO_TAG_NAME.StartsWith("release-")) {
        echo "Updating version information for this release." 
      }


deploy:
  release: "Bookworm Release (Build v$(appveyor_build_version))"
  description: "Uploaded from appveyor by the build bot"
  provider: GitHub
  auth_token:
    secure: "ogfTv7V0xR13ETjrC+koS7ZURfl0KLRfwcjYBexoiB1gcc5pppO/H42BopJWl0ua"
  artifact: /Bookworm-.*-setup\.exe/, /Bookworm-.*-update\.bundle/, /Bookworm-.*-portable\.zip/, /release-info\.json/
  draft: true
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true

notifications:
 - provider: GitHubPullRequest
   on_build_status_changed: false
   template: |-
    {{#passed}}Build succeeded!{{/passed}}{{#failed}}Build failed!{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})
    {{#passed}}Downloads:{{#jobs}}
    <details>
    <summary>{{name}}</summary>

    {{#artifacts}}
    - [{{fileName}}]({{permalink}})
    {{/artifacts}}
    </details>
    {{/jobs}}{{/passed}}
